  module.exports = {
    "branch":{
      "val1":"El uuid no debe estar vacio",
      "val2":"El uuid debe ser una cadena",
    },
    "authentication":{
        "val1": "El identificador del token no debe estar vacio",
        "val2": "El identificador del token debe ser cadena",
        "val3": "El identificador del usuario no debe estar vacio",
        "val4": "El identificador del usuario debe ser cadena",
        "val5": "El identificador del token debe ser cadena",
        "val6": "El identificador del token debe ser cadena"
    },
    "users":{
      "val1": "el identificador del usuario debe ser un identificador de mongo",
      "val2": "Los nombres del usuario debe ser una cadena",
      "val3": "Los nombres del usuario no debe estar vacio",
      "val4": "Los apellidos del usuario debe ser una cadena",
      "val5": "Los apellidos del usuario no debe estar vacio",
      "val6": "El identificador de compañia debe ser una cadena",
      "val7": "El identificador de compañía no debe estar vacio",
      "val8": "El identificador de la sucursal es inválido debido que no tiene un identificador de compañia",
      "val9": "El identificador de la sucursal debe ser una cadena",
      "val10": "El identificador de la sucursal no debe estar vacio",
      "val11": "El nombre de la sucursal es inválido debido que no tiene un identificador",
      "val12": "El nombre de la sucursal debe ser cadena",
      "val13": "El nombre de la sucursal no debe estar vacio",
      "val14": "El nombre de la compañía es invalid debido que no tiene un identificador",
      "val15": "El nombre de la compañía debe ser cadena",
      "val16": "El nombre de la compañía no debe estar vacío",
      "val17": "La disponibilidad debe ser booleano",
      "val18": "El estado del usuario debe ser: NEW, QUEUE, CHECKING, UNABLE, ABLE, INACTIVE",
      "val19": "El limite del query debe ser entero",
      "val20": "El salto del query debe ser entero",
      "val21": "El estado del usuario debe ser: NEW, QUEUE, CHECKING, UNABLE, ACTIVE, INACTIVE",
      "val22": "El usuario de Id debe ser una cadena",
      "val23": "El usuario de Id no debe estar vacio",
      "val24": "el tipo de usuario debe ser: WILDCARD, AVAILABLE, PERMANENT",
      "val25": "eL identificador de la sucursal debe ser UUID",
      "val26": "el identificador de compañia debe ser UUID",
      "val27": "el identificador de la compañia debe tener la sucursal",
      "val28": "el telefono debe ser númerico",
      "val29": "si se asigna un tipo fijo debe asignarse una sucursal"
    }
}